### ISSUE TITLE
pst-barcode interacts with forest in unpleasent ways

### ISSUE THREAD

**Issue by stefan11** [langsci/langscibook#113] opened 2020-05-13 07:56 UTC
pst-barcodes causes lines to be drawn all over the page when a forest tree is drawn. This stabalizaes after several runs, but we have decided to replace the package. I tried to use ean13isbn:
```latex
    \colorbox{white}{
      \begin{pspicture}(0,0)(4.1,1in)
        %\psbarcode[transx=.4,transy=.3]{\lsISBNcover}{includetext height=.7}{isbn}%
        \EANisbn[SC5b,ISBN=\lsISBNcover]
      \end{pspicture}
      }
```
with and without the `pspicture` but this did not work. Could somebody please take care of this?

**Comment by Glottotopia** [comment] 2020-05-13 08:39
you can try the following: 
- uncomment `pst-barcodes`
- add `\usepackage[ISBN=9788085955354]{ean13isbn}` to your preamble
- around line 381 of `langscibook.cls`, add
```
  \EANisbn
%       \begin{pspicture}(0,0)(4.1,1in)
%         \psbarcode[transx=.4,transy=.3]{\lsISBNcover}{includetext height=.7}{isbn}%
%       \end{pspicture}
```
For some reason, the ISBN has to be entered as digits. I cannot use `\lsISBNdigital`.

I am not sure how this interacts with dust jacket generation, but we could load pst-barcodes only if one of the BoD options is active @kopeckyf

**Comment by kopeckyf** [comment] 2020-05-13 09:29
> pst-barcodes causes lines to be drawn all over the page when a forest tree is drawn

Could you please post a MWE that shows this error? If this is true, the developer of `pst-barcode` needs to be notified.

**Comment by stefan11** [comment] 2020-05-13 11:00
It is erratic. But I will try. It was in the books for years now and I struggled with this. Talked to Roland Schäfer today and he had the problem too.

**Comment by kopeckyf** [comment] 2020-05-13 11:21
We need something definite, a "smoking gun" so to speak. From what we know so far, the problem could be related to almost anything that is happening in your book.

**Comment by Glottotopia** [comment] 2020-10-23 13:35
Unless there is a reproducible MWE in the near future, we will close this issue soon

**Comment by stefan11** [comment] 2020-10-26 19:48
I am sorry, I cannot track this. Saso said it is due to remeber pic from tikz.

**Comment by Glottotopia** [comment] 2020-10-27 07:06
can't reproduce

**Closed by Glottotopia** 2020-10-27 07:06 UTC
